version: '3.8'

services:
  db:
    container_name: mysql_db
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: comandas
      MYSQL_USER: 1234
      MYSQL_PASSWORD: 1234
    volumes:
      - ./data:/var/lib/mysql
    restart: always